WOD = {
    'ATR': ('Attributes', "Traits that measure a character's innate capabilities, grouped into three categories: Physical, Social and Mental."),
    'SKI': ('Skills', "Traits that represent a character's acquired capabilities."),
    'EXP': ('Experience', 'Experience points are used to measure character advancement over time.'),

    'Str': ('Strength', "Physical Power. Directly contributes to a character's Speed trait."),
    'Dex': ('Dexterity', "Physical Finesse. Directly contributes to a character's Speed trait, and affects a character's Defense trait."),
    'Sta': ('Stamina', "Physical Resistance. Directly contributes to a character's Health trait."),
    'Pre': ('Presence', 'Social Power.'),
    'Man': ('Manipulation', 'Social Finesse.'),
    'Com': ('Composure', "Social Resistance; the ability to stay focused and calm under emotional pressure, and to resist emotional manipulation. Directly contributes to a character's Willpower trait, and used with Wits for perception related tasks."),
    'Int': ('Intelligence', "Mental Power."),
    'Wit': ('Wits', "Mental Finesse. Used with Composure for perception related tasks, and affects a character's Defense trait."),
    'Res': ('Resolve', "Mental Resistance; a character's strength of will and intellectual focus. Directly contributes to a character's Willpower trait."),

    'ath': ('Athletics', 'sports and movement'),
    'bra': ('Brawl', 'unarmed combat'),
    'dri': ('Drive', 'operating automobiles'),
    'fir': ('Firearms', 'identifying, using, and maintaining firearms and bows'),
    'lar': ('Larceny', 'picking locks, burglary, bypassing security, sleight of hand, etc'),
    'ste': ('Stealth', 'moving silently and unnoticed'),
    'sur': ('Survival', 'enduring harsh environments'),
    'wea': ('Weaponry', 'identifying, using, and maintaining non-firearm weapons'),
    'aca': ('Academics', 'knowledge in Arts and Humanities'),
    'com': ('Computer', 'computer programs and operating systems'),
    'cra': ('Crafts', 'constructing, crafting, and repairing objects'),
    'inv': ('Investigation', 'solving riddles and finding evidence'),
    'med': ('Medicine', 'physiology, anatomy, and medical treatments'),
    'occ': ('Occult', 'lore about the supernatural'),
    'pol': ('Politics', 'political processes and bureaucratic maneuvers'),
    'sci': ('Science', 'physical and natural sciences'),
    'ani': ('Animal Ken', 'understanding animal minds and behaviors'),
    'emp': ('Empathy', 'observing emotions and understanding viewpoints'),
    'exp': ('Expression', 'art of communication and entertainment'),
    'int': ('Intimidation', 'coercing via force and threat'),
    'per': ('Persuasion', 'convincing others and inspiring their emotions'),
    'soc': ('Socialize', 'social interaction in various situations'),
    'str': ('Streetwise', 'navigating urban streets and gathering intel there'),
    'sub': ('Subterfuge', 'deceiving others and noticing it')

}